Nostrademous/Dota2-FullOverwrite

role.lua
Added some comments. It should explain my reason of some heroes you may find weird in that role / you would put into another role / is missing from a role.
Added all intelligence heroes.
Final touches for this night - 12:00 AM in Germany. Good night everybody!
=> Edited role.lua

item_purchase_viper.lua
Basic implementation of Viper item purchasing, probably needs some fleshing out, but it's a start
=> started work on viper item purchasing

item_purchase_generic_test.lua, items.lua
Also in this pull request: items.lua tables reorganized (reordered items), attempt to get selling items to work (however that is not enabled atm)
=> Fixed nested items not being bought

item_usage.lua
Checks whether me or allied heroes health below 15%, if either is true, activate mekansm
- Might need some more tweak to check whether allied heroes has mekansm buff or not.
- Also, I think it's better to ensure that each team only has 1 mekansm.
=> Pull request for issue #43 Add Mekansm usage

item_purchase_generic_test.lua
Also added removing the parts once the item is completely on the purchase table.
=> Fixed bought items not being used

item_usage.lua, modifiers.lua, utility.lua
- added a new file named "modifiers.lua" which contains a basic list of DoT modifiers. 
- added a condition that checks if a bot is under a DoT Debuff before using flask or clarity
=> [Issue #65] Pull Request

ability_usage_bloodseeker.lua, bot_bloodseeker.lua, ganking_generic.lua, jungling_generic.lua
=> Slight improvements to BS ganking

item_purchase_generic_test.lua, items.lua
with purchase routes like first ring of basilius then ring of aquila (resulted in buying ring of basilius again in before). Selling considers inventory and backpack.
=> Enabled selling, fixed nested item bug..

ability_usage_drow_ranger.lua, bot_bloodseeker.lua, bot_drow_ranger.lua, modifiers.lua
- drow now can jungle normally. seems like the retreat function is not
working for drow jungler
- fixed values for bloodrage heal percentages
=> [FIXES] Various fixes for bloodseeker and drow bot

item_purchase_generic_test.lua, utility.lua
Added round function to utility, rounding gametime to 3 decimals now.
Added option to filter by botname.
=> Changed print to myPrint

ability_usage_drow_ranger.lua, bot_drow_ranger.lua, item_purchase_drow_ranger.lua
- added logic to use Trueshot active when pushing
- changed drow items to new system
- improve lane harassment
- added additional condition before using frost arrows, does not use
frost arrows on stunned and rooted enemies for mana efficiency
-- TODO: use GetAttackTarget() to check if drow is attacking a tower before using trueshot. Not sure if this is better than the current though
=> Various improvements for drow ranger

bot_bloodseeker.lua
- bloodseeker bot now calculates total damage output by all neutral
creeps nearby
=> [Issue #84] Bloodseeker bot improvements

buildings_status.lua, decision_tree.lua, ganking_generic.lua, global_game_state.lua, utility.lua
Wasn't able to test everything to the last detail. But it seems to work.
=> keep track of building. preparations for map wide tower planning

ability_usage_drow_ranger.lua, bot_drow_ranger.lua, decision_tree.lua, item_purchase_drow_ranger.lua, item_usage.lua, utility.lua
- fixed bots not initializing when human plays versus bots
=> Minor changes

ability_usage_drow_ranger.lua
- updated code to comply with changes
- modified how drow uses her gust to cast on heroes with stun
- drow can now use gust on chasing enemies
=> [Issue #119] Drow - Gust Use

decision_tree.lua, item_usage.lua
[Issue #94] Use consumable healing items to allies
- added UseRegenItemsOnAlly
- added Urn of Shadows in regen items
[Issue #62] Implement Determine_ShouldTeamRoshan() Function
- made a basic and rough implementation that checks if enemies are dead
and if the remaining alive heroes are less than 3
=> Fixes for [Issue #94] and [Issue #62]

utility.lua
- added z-axis check for nearest tree
=> [Issue #132] Tango Use - Check Z-Axis for nearest Tree

ability_usage_antimage.lua, ability_usage_lina.lua, ability_usage_viper.lua, bot_bloodseeker.lua, decision_tree.lua, fight_simul.lua, item_usage.lua, utility.lua
- updated GetActualDamage -> GetActualIncomingDamage
- can now use tp even when inventory is full, uses backpack switching to
use tp
=> Various fixes

role.lua
She seemed to have made some mistakes, or forgot stuff...
=> Added comments off ByBurton

hero_selection.lua
Dire (valve bots) now has a defensive trilane, and a zuus mid instead of bounty hunter.
1vs1 mid is now Lina and drow instead of abyssal underlord?!?! and drow?
-> Better and more useful testing results
=> Changes to hero_selection for more useful testing

debugging.lua, decision_tree.lua
Felt like I'm gonna need something more structured than console spamming for the lane push/defend stuff.
It prints on the right site of the screen. Currently configured to be used with a 1920x1080.
=> Add state displaying for debugging purposes

abilityUse/abilityUse_phantom_assassin.lua
Divided by 100 (cause percentage)
=> Fixed pa dagger damage calc
